// Lecture-order schedule data, generated by pipeline/_scripts/sync-plan.ts into
// data/schedule.json. The book's chapter structure is the logical presentation;
// the course visits topics in lecture order — this powers /schedule/ and the
// per-topic lecture badges that make the dual ordering visible to students.
import fs from 'fs';
import path from 'path';

export interface ScheduleItem {
  num: string | null;      // book section number ("3.0.0"); null for no-content rows
  title: string;
  slug: string | null;     // null for no-content rows (exam days, review days)
  type: string;            // "full" | "content-only" | "no-content"
  published: boolean;      // only published topics get links
}

export interface Lecture {
  lec: number;
  date: string | null;     // ISO date, derived from schedule.json (holiday-aware)
  weekday: string | null;
  items: ScheduleItem[];
}

export interface ScheduleData {
  generated: string;
  lectures: Lecture[];
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export function loadSchedule(): ScheduleData | null {
  const p = path.join(process.cwd(), 'data', 'schedule.json');
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8')) as ScheduleData;
  } catch {
    return null;
  }
}

export function prettyDate(iso: string | null): string | null {
  if (!iso) return null;
  const [y, m, d] = iso.split('-').map(Number);
  if (!y || !m || !d) return null;
  return `${MONTHS[m - 1]} ${d}`;
}

/** Which lecture (if any) covers this topic slug. */
export function lectureForSlug(data: ScheduleData | null, slug: string): Lecture | null {
  if (!data) return null;
  for (const lecture of data.lectures) {
    if (lecture.items.some((i) => i.slug === slug)) return lecture;
  }
  return null;
}
