// Lecture-order schedule data, generated by pipeline/_scripts/sync-plan.ts into
// data/schedule.json. The book's chapter structure is the logical presentation;
// the course visits topics in lecture order — this powers /schedule/ and the
// per-topic lecture badges that make the dual ordering visible to students.
import fs from 'fs';
import path from 'path';

export interface ScheduleItem {
  num: string | null;      // book section number ("3.0.0"); null for no-content rows
  title: string;
  slug: string | null;     // null for no-content rows (exam days, review days)
  type: string;            // "full" | "content-only" | "no-content"
  published: boolean;      // only published topics get links
}

export interface Lecture {
  lec: number;
  date: string | null;     // ISO date, derived from schedule.json (holiday-aware)
  weekday: string | null;
  items: ScheduleItem[];
}

export interface ScheduleData {
  generated: string;
  lectures: Lecture[];
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export function loadSchedule(): ScheduleData | null {
  const p = path.join(process.cwd(), 'data', 'schedule.json');
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8')) as ScheduleData;
  } catch {
    return null;
  }
}

export function prettyDate(iso: string | null): string | null {
  if (!iso) return null;
  const [y, m, d] = iso.split('-').map(Number);
  if (!y || !m || !d) return null;
  return `${MONTHS[m - 1]} ${d}`;
}

/** Which lecture (if any) covers this topic slug. */
export function lectureForSlug(data: ScheduleData | null, slug: string): Lecture | null {
  if (!data) return null;
  for (const lecture of data.lectures) {
    if (lecture.items.some((i) => i.slug === slug)) return lecture;
  }
  return null;
}

export interface LectureNeighbor {
  slug: string;
  title: string;
  lec: number;          // which lecture the neighbor belongs to
  sameLecture: boolean; // false when the step crosses into another lecture
}

/** Flatten the schedule into one course-ordered list of published, linkable topics. */
function flatLectureOrder(data: ScheduleData): { slug: string; title: string; lec: number }[] {
  const flat: { slug: string; title: string; lec: number }[] = [];
  for (const lecture of data.lectures) {
    for (const item of lecture.items) {
      if (item.slug && item.published) flat.push({ slug: item.slug, title: item.title, lec: lecture.lec });
    }
  }
  return flat;
}

function lectureNeighbor(data: ScheduleData | null, slug: string, step: 1 | -1): LectureNeighbor | null {
  if (!data) return null;
  const flat = flatLectureOrder(data);
  const ix = flat.findIndex((f) => f.slug === slug);
  if (ix < 0) return null;
  const jx = ix + step;
  if (jx < 0 || jx >= flat.length) return null;
  const neighbor = flat[jx];
  return { ...neighbor, sameLecture: neighbor.lec === flat[ix].lec };
}

/** The next topic in LECTURE order (course order), skipping unpublished topics and
 *  no-content rows. Null when the topic isn't scheduled or is the course's last. */
export function nextInLectureOrder(data: ScheduleData | null, slug: string): LectureNeighbor | null {
  return lectureNeighbor(data, slug, 1);
}

/** The previous topic in LECTURE order — the mirror of nextInLectureOrder. */
export function prevInLectureOrder(data: ScheduleData | null, slug: string): LectureNeighbor | null {
  return lectureNeighbor(data, slug, -1);
}
