title: "Basic Logic Gates"
description: "AND, OR, NOT, NAND, NOR, XOR, and XNOR gates with truth tables, symbols, and Boolean expressions"
order: 1

graphics:
  01-basic-gates-video.youtube:
    caption: "Video introduction to basic logic gates"
  02-logic-gates.html:
    caption: "Interactive logic gate simulator - click truth table rows to see gate behavior"
