title: "Analog to Digital Conversion"
description: "How sampling and quantization transform continuous real-world signals into discrete binary representations that digital systems can process."
order: 2

graphics:
  01-digital-vs-analog.html:
    caption: "Interactive visualization of sampling and quantization"
  02-atod-video.youtube:
    caption: "Video: Analog to Digital Conversion"
