title: "Vinyl, Digital, and the Cost of Convenience"
description: "How the shift from vinyl to digital music illustrates that technical improvement and experiential loss can occur at the same time — and why constraints matter in system design."
order: 4

graphics:
  01-vinyl-art-gallery.html:
    caption: "Interactive: 12 iconic album covers that used the vinyl format as a canvas"
