title: "De Morgan's Theorem and Universal Gates"
description: "How De Morgan's theorem enables efficient NAND-only and NOR-only circuit implementations"
order: 2

graphics:
  01-demorgans-video.youtube:
    caption: "Video introduction to De Morgan's theorem and universal gates"
  02-demorgans-interactive.html:
    caption: "Interactive demonstration - click truth table rows to verify gate equivalences"
