title: "S-R Latch and S'-R' Latch"
description: ""
chapter: sequential-logic
section: memory-elements
order: 40102

graphics:
  01-video.youtube:
    caption: "Video: S-R Latch"
  02-interactive.html:
    caption: "Interactive: S-R Latch"
  03-interactive.html:
    caption: "Interactive: S-R Latch"
  04-interactive.html:
    caption: "Interactive: S-R Latch"
